import os

CCWEB_DIR = os.environ['VRAG_PATH_CCWEB_DIR']
EVVE_DIR = os.environ['VRAG_PATH_EVVE_DIR']
FIVR5K_DIR = os.environ['VRAG_PATH_FIVR5K_DIR']
FIVR200K_DIR = os.environ['VRAG_PATH_FIVR200K_DIR']
VCDB_DIR = os.environ['VRAG_PATH_VCDB_DIR']
VCDB_DISTRACTOR_DIR = os.environ['VRAG_PATH_VCDB_DISTRACTOR_DIR']
TRAIN_DATA_DIR = os.environ['VRAG_PATH_TRAIN_DATA_DIR']
CHECKPOINT_DIR = os.environ['VRAG_PATH_CHECKPOINT_DIR']

CONFIG_DIR = os.environ['VRAG_PATH_CONFIG_DIR']
LOG_DIR = os.environ['VRAG_PATH_LOG_DIR']
RESULT_DIR = os.environ['VRAG_PATH_RESULT_DIR']
